name: Upgrde Appsmith Test Workflow

on:
  # This line enables manual triggering of this workflow.
  workflow_dispatch:
    inputs:
      pr:
        description: "This is the PR number in case the workflow is being called in a pull request"
        required: false
        type: number
        default: 27568

jobs:
  ci-test-result:
    if: always()
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Dump the client payload context
        env:
          PAYLOAD_CONTEXT: ${{ toJson(github.event.client_payload) }}
        run: echo "$PAYLOAD_CONTEXT"

      # Check out merge commit with the base branch in case this workflow is invoked via pull request
      - name: Checkout the merged commit from PR and base branch
        if: inputs.pr != 0
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: refs/pull/${{ inputs.pr }}/merge

      # get all the files changes in the cypress/e2e folder    
      - name: Get all the added or changed files in client/src folder
        if: inputs.pr != 0
        id: files
        uses: umani/changed-files@v4.0.0
        with:
          repo-token: ${{ secrets.APPSMITH_CI_TEST_PAT }}
          pattern: 'app/client/src/.*'
          pr-number: ${{ inputs.pr }}

      # Check all the newly added files are in ts  
      - name: Check the newly added files are written in ts
        if: inputs.pr != 0
        id: check_files
        run: |
          comment_files=""
          files=(${{steps.files.outputs.files_created}}${{steps.files.outputs.files_updated}})
          for file in $files; do
              while IFS= read -r line; do
                if echo "$line" | grep -q 'color/Color.*#'; then
                  comment_files="$comment_files,$file"
                fi
              done < "$file"
          done
          echo "${comment_files#,}"
